FILES=Percolation.java PercolationStats.java

all:$(FILES)
	javac-algs4 $(FILES)

zip:$(FILES)
	zip percolation.zip $(FILES)

add:$(FILES)
	git add $(FILES) Percolation_two_WQUUF.java MyPercolation.java Makefile Readme.md

clean:
	rm *.class *.zip
